// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialVeterinarySurgeon.DAL;

namespace SocialVeterinarySurgeon.DAL.Migrations
{
    [DbContext(typeof(SocialVeterinarySurgeonDbContext))]
    partial class SocialVeterinarySurgeonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SocialVeterinarySurgeon.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("FromMediaInteractiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromMediaInteractiva = false,
                            LastName = "Smith",
                            Name = "John"
                        },
                        new
                        {
                            Id = 2,
                            FromMediaInteractiva = false,
                            LastName = "Heafy",
                            Name = "Matt"
                        });
                });

            modelBuilder.Entity("SocialVeterinarySurgeon.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Max",
                            OwnerId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Garfield",
                            OwnerId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Miyuki",
                            OwnerId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Karl",
                            OwnerId = 2,
                            Type = 2
                        });
                });

            modelBuilder.Entity("SocialVeterinarySurgeon.Domain.Entities.Pet", b =>
                {
                    b.HasOne("SocialVeterinarySurgeon.Domain.Entities.Employee", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
